"use client";
import {useEffect,useMemo,useState} from "react";
type Outcome="worked"|"partial"|"failed"|"pending";
type Attempt={id:string;title:string;notes:string;outcome:Outcome;date:string};
type Project={id:string;title:string;context:string;attempts:Attempt[];updatedAt:string};
const meta:Record<Outcome,{label:string;icon:string}>={worked:{label:"Worked",icon:"✓"},partial:{label:"Partly worked",icon:"~"},failed:{label:"Didn't work",icon:"×"},pending:{label:"Still testing",icon:"…"}};
const sample:Project={id:"sample",title:"Fixing my afternoon energy crash",context:"I lose focus around 3pm, especially after a heavy lunch.",updatedAt:new Date().toISOString(),attempts:[{id:"s1",title:"Extra coffee after lunch",notes:"More alert, but sleep was worse.",outcome:"failed",date:"2026-08-18"},{id:"s2",title:"15-minute walk",notes:"Noticeably better focus for about two hours.",outcome:"worked",date:"2026-08-19"},{id:"s3",title:"Lighter lunch",notes:"Promising, trying for another week.",outcome:"pending",date:"2026-08-20"}]};
const id=()=>Math.random().toString(36).slice(2,9);
export default function Home(){
 const [projects,setProjects]=useState<Project[]>([]),[activeId,setActiveId]=useState(""),[loaded,setLoaded]=useState(false),[modal,setModal]=useState<"new"|"attempt"|"share"|null>(null),[toast,setToast]=useState(""),[query,setQuery]=useState("");
 useEffect(()=>{const s=localStorage.getItem("alreadytried.projects");const p=s?JSON.parse(s):[sample];setProjects(p);setActiveId(p[0]?.id||"");setLoaded(true)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem("alreadytried.projects",JSON.stringify(projects))},[projects,loaded]);
 const active=projects.find(p=>p.id===activeId)||projects[0];
 const shown=useMemo(()=>active?.attempts.filter(a=>(a.title+" "+a.notes).toLowerCase().includes(query.toLowerCase()))||[],[active,query]);
 const flash=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2200)};
 const addProject=(f:FormData)=>{const title=String(f.get("title")||"").trim();if(!title)return;const p={id:id(),title,context:String(f.get("context")||""),attempts:[],updatedAt:new Date().toISOString()};setProjects(x=>[p,...x]);setActiveId(p.id);setModal(null);flash("List created")};
 const addAttempt=(f:FormData)=>{if(!active)return;const title=String(f.get("attempt")||"").trim();if(!title)return;const a:Attempt={id:id(),title,notes:String(f.get("notes")||""),outcome:String(f.get("outcome")) as Outcome,date:String(f.get("date"))};setProjects(x=>x.map(p=>p.id===active.id?{...p,attempts:[a,...p.attempts],updatedAt:new Date().toISOString()}:p));setModal(null);flash("Attempt logged")};
 const outcome=(aid:string,o:Outcome)=>setProjects(x=>x.map(p=>p.id===active?.id?{...p,attempts:p.attempts.map(a=>a.id===aid?{...a,outcome:o}:a)}:p));
 const remove=(aid:string)=>{setProjects(x=>x.map(p=>p.id===active?.id?{...p,attempts:p.attempts.filter(a=>a.id!==aid)}:p));flash("Entry removed")};
 const summary=active?`${active.title}\n${active.context?`Context: ${active.context}\n`:""}\nAlready tried:\n${active.attempts.map(a=>`• ${a.title} — ${meta[a.outcome].label}${a.notes?`: ${a.notes}`:""}`).join("\n")||"Nothing logged yet."}`:"";
 const copy=async()=>{await navigator.clipboard.writeText(summary);setModal(null);flash("Summary copied")};
 const counts=active?.attempts.reduce((n,a)=>({...n,[a.outcome]:n[a.outcome]+1}),{worked:0,partial:0,failed:0,pending:0})||{worked:0,partial:0,failed:0,pending:0};
 if(!loaded)return <main className="loading">Opening your lists…</main>;
 return <main>
  <header className="topbar"><a className="brand" href="#top"><span>AT</span>AlreadyTried</a><div className="top-actions"><small>● Saved privately on this device</small><button className="btn ghost" onClick={()=>setModal("new")}>＋ New list</button></div></header>
  <section className="hero" id="top"><div className="eyebrow">Stop repeating yourself</div><h1>Remember what you<br/><em>already tried.</em></h1><p>Keep the attempts, outcomes and useful context in one simple place. Share the full picture in seconds—then move forward.</p><div className="hero-actions"><button className="btn primary large" onClick={()=>setModal("new")}>Start a new list　→</button><a href="#workspace">See how it works ↓</a></div><div className="pills"><small>Useful for</small><b>Troubleshooting</b><b>Health notes</b><b>Buying decisions</b><b>Work experiments</b></div></section>
  <section className="workspace" id="workspace"><aside><div className="side-title">YOUR LISTS <button onClick={()=>setModal("new")}>＋</button></div><div className="projects">{projects.map(p=><button key={p.id} className={p.id===active?.id?"active":""} onClick={()=>{setActiveId(p.id);setQuery("")}}><i>{p.title[0]}</i><span><strong>{p.title}</strong><small>{p.attempts.length} attempts</small></span></button>)}</div><button className="new-side" onClick={()=>setModal("new")}>＋ Create another list</button></aside>
  <div className="content">{active?<><div className="content-head"><div><small>ACTIVE LIST</small><h2>{active.title}</h2><p>{active.context||"Add each thing you try and record what happened."}</p></div><div><button className="btn ghost" onClick={()=>setModal("share")}>↗ Share summary</button><button className="btn primary" onClick={()=>setModal("attempt")}>＋ Log an attempt</button></div></div>
  <div className="stats"><div><b>{active.attempts.length}</b><small>Total attempts</small></div><div className="green"><b>{counts.worked}</b><small>Worked</small></div><div className="amber"><b>{counts.pending+counts.partial}</b><small>In progress</small></div><div className="red"><b>{counts.failed}</b><small>Didn't work</small></div></div>
  <div className="attempt-head"><h3>ATTEMPTS</h3><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search what you tried…"/></label></div><div className="attempts">{shown.map(a=><article key={a.id}><i className={a.outcome}>{meta[a.outcome].icon}</i><div><h4>{a.title}</h4><p>{a.notes||"No notes added."}</p><small>{new Date(a.date+"T12:00:00").toLocaleDateString("en",{day:"numeric",month:"short",year:"numeric"})}</small></div><select value={a.outcome} onChange={e=>outcome(a.id,e.target.value as Outcome)}><option value="worked">Worked</option><option value="partial">Partly worked</option><option value="failed">Didn't work</option><option value="pending">Still testing</option></select><button className="delete" onClick={()=>remove(a.id)}>×</button></article>)}{!shown.length&&<div className="empty"><h3>{query?"No matching attempts":"Nothing tried yet"}</h3><p>{query?"Try another search.":"Log your first attempt and its outcome."}</p>{!query&&<button className="btn primary" onClick={()=>setModal("attempt")}>Log an attempt</button>}</div>}</div></>:<div className="empty"><h2>Create your first list</h2><button className="btn primary" onClick={()=>setModal("new")}>Get started</button></div>}</div></section>
  <section className="how"><div className="eyebrow">One tiny habit, less wasted time</div><h2>Your history becomes a shortcut.</h2><div className="steps"><div><b>01</b><h3>Name the problem</h3><p>Create a focused list for one decision, issue or goal.</p></div><div><b>02</b><h3>Log each attempt</h3><p>Record the result while the details are still fresh.</p></div><div><b>03</b><h3>Share the context</h3><p>Copy a clean summary before asking anyone for advice.</p></div></div></section>
  <footer><a className="brand" href="#top"><span>AT</span>AlreadyTried</a><p>No account. No tracking. Your lists stay in your browser.</p><small>Built to help you move forward.</small></footer>
  {modal==="new"&&<Modal title="Start a new list" sub="One list works best for one clear problem or decision." close={()=>setModal(null)}><form action={addProject}><label>What are you working on?<input name="title" autoFocus required placeholder="e.g. Finding a better morning routine"/></label><label>Helpful context <small>Optional</small><textarea name="context" placeholder="What matters? What constraints should others know?"/></label><Actions close={()=>setModal(null)} submit="Create list →"/></form></Modal>}
  {modal==="attempt"&&<Modal title="What did you try?" sub={`Add an attempt to “${active?.title}”.`} close={()=>setModal(null)}><form action={addAttempt}><label>Attempt<input name="attempt" autoFocus required placeholder="Describe what you tried"/></label><label>What happened?<textarea name="notes" placeholder="Add the useful detail, result or lesson…"/></label><div className="form-row"><label>Outcome<select name="outcome" defaultValue="pending"><option value="pending">Still testing</option><option value="worked">Worked</option><option value="partial">Partly worked</option><option value="failed">Didn't work</option></select></label><label>Date<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label></div><Actions close={()=>setModal(null)} submit="Save attempt →"/></form></Modal>}
  {modal==="share"&&<Modal title="Your ready-to-share summary" sub="Copy it into a message, forum post, appointment note or AI chat." close={()=>setModal(null)}><textarea className="summary" readOnly value={summary}/><div className="actions"><button className="btn ghost" onClick={()=>setModal(null)}>Close</button><button className="btn primary" onClick={copy}>Copy summary</button></div></Modal>}{toast&&<div className="toast">✓ {toast}</div>}
 </main>}
function Modal({title,sub,close,children}:{title:string;sub:string;close:()=>void;children:React.ReactNode}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><button className="close" onClick={close}>×</button><h2>{title}</h2><p>{sub}</p>{children}</div></div>}
function Actions({close,submit}:{close:()=>void;submit:string}){return <div className="actions"><button type="button" className="btn ghost" onClick={close}>Cancel</button><button className="btn primary">{submit}</button></div>}
